// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/template-mono/app/user/internal/dao/internal"
)

// internalTUserDao is internal type for wrapping internal DAO implements.
type internalTUserDao = *internal.TUserDao

// tUserDao is the data access object for table t_user.
// You can define custom methods on it to extend its functionality as you wish.
type tUserDao struct {
	internalTUserDao
}

var (
	// TUser is globally public accessible object for table t_user operations.
	TUser = tUserDao{
		internal.NewTUserDao(),
	}
)

// Fill with you ideas below.
